#!/bin/sh
set -e
dl_tool="$(dirname $0)/dl-graalvm"
url="https://api.github.com/repos/graalvm/graalvm-ce-builds/releases/latest"
echo "getting: $url" >&2
latest=$(curl "$url")
tag_name=$(echo "$latest" | jq -r .tag_name)
install_dir=$("$dl_tool" "$tag_name")
install_sym=$(realpath "${install_dir}/../latest")
rm -f "$install_sym"
ln -s "$(basename $install_dir)" "$install_sym"
echo "$install_sym"