#!/bin/sh
set -e
dl_tool="$(dirname $0)/dl-gradle"
url="https://services.gradle.org/versions/current"
echo "getting: $url" >&2
current=$(curl "$url")
version=$(echo "$current" | jq -r .version)
install_dir=$("$dl_tool" "$version")
install_sym="${install_dir}/../current"
rm -f "$install_sym"
ln -s "$(basename $install_dir)" "$install_sym"
