#!/bin/sh
set -e
dl_tools=${DL_TOOLS:-${XDG_STATE_HOME:-$HOME/.local/state}/dl-tools}
dl_home=${DL_TOOLS_GRAALVM:-${dl_tools}/graalvm}
tag_name=${1:?missing argument <tag_name>}
arch=$(uname -m)
[ "$arch" = x86_64 ] && arch=x64
os=linux
archive_name="graalvm-community-${tag_name}_$os-${arch}_bin.tar.gz"
link="https://github.com/graalvm/graalvm-ce-builds/releases/download/$tag_name/$archive_name"
url="$link.sha256"
echo "getting: $url" >&2
checksum=$(curl -L "$url")
echo "$checksum" | base64 -d > /dev/null
release_dir="${dl_home}/${tag_name}"
mkdir -p "$release_dir"
(
    flock 9
    if [ ! -e "${release_dir}/bin" ]; then
        archive_file="${dl_home}/${archive_name}"
        checksum_file="${archive_file}.checksum"
        echo "$checksum *$archive_file" > "$checksum_file"
        [ ! -e "$archive_file" ] || sha256sum -c "$checksum_file" >&2 || rm "$archive_file"
        if [ ! -e "$archive_file" ]; then
            echo "downloading: $link" >&2
            curl -Lo "$archive_file" "$link"
        fi
        sha256sum -c "$checksum_file" >&2
        tar -C "$release_dir" -xzf "$archive_file"
        rm "$archive_file"
        rm "$checksum_file"
        archive_dir=$(echo "$release_dir"/*)
        mv "$archive_dir"/* "$release_dir"
        rmdir "$archive_dir"
    fi
) 9<"$release_dir"
echo "$release_dir"
